version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: "a-nginx"
    volumes:
      - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/dev/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "80:80"
     - "443:443"

  mysql:
    image: mysql:5.7
    container_name: "a-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: "Asia/Bangkk"
  
  redis:
    image: redis:alpine
    container_name: "a-redis"

  apollo:
    build: docker/apollo
    container_name: "apollo"
    ports:
      - "80"
    environment:
      DB_DATABASE: "spanky"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_HOST: "mysql"
    volumes:
      - ./docker/apollo/code:/var/www
